version: "3.8"

services:
  chaobum-db:
    image: mysql:8.0.34
    env_file:
      - ./docker/mysql.env
    container_name: "chaobum-db"
    volumes:
      - ./docker/conf/mysql.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./docker/data:/var/lib/mysql
      - ./docker/logs:/var/log/mysql
    ports:
      - "6606:3306"
